### ISSUE TITLE
feature request: run against hashes.org

### ISSUE THREAD

**Issue by roycewilliams** [rarecoil/pantagrule#1]
Many of the HIBP corpus is corrupted, in the wrong character encoding, wrapped in HTML tags, or otherwise useless for actual password-cracking purposes.

Please consider running the same analysis against a higher-quality corpus, such as the hashes.org founds.

**Comment by rarecoil** [comment]
To clarify, you're looking to get the "optimised variants" of `pantagrule.1m` using a hashed version of the plaintext of https://github.com/rarecoil/hashes.org-list as the target? That list will contain almost the entirety of HIBP as well, since hashes.org has cracked approximately 99.5% of it.

**Comment by roycewilliams** [comment]
Correct. My assumption is that the resulting ruleset will be different in both order/frequency and in size, both of which will produce increased efficiency in real-world attacks.

**Comment by rarecoil** [comment]
There's only one way to find out. I'll try this and add data/changes back to this repository. It will likely take a bit of time, as I'm down some hardware from when this was originally created, and some of my GPU resources are handling COVID-19 tasks.

**Comment by rarecoil** [comment]
Added new optimisations to Pantagrule, along with an explanation as to why they exist. Thanks @roycewilliams for your request.

**Comment by roycewilliams** [comment]
Thanks for the quick turnaround - and for the name, though I may never live it down! :laughing:
